let name = ["abir","rohim","korim"];
let number = [2,4,5];
// console.log(name[1],number[1]);
// name .push("zodu");
// name.push("abul");
// name.push("kabul");
// name.pop();
// name.unshift("kabul");
// name.shift();
name.splice(1,0,"akbor");
name.splice(3,0,"motlob");
console.log(name);